[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors 'self' https://yohelab.netlify.app https://yohelab-demo.netlify.app http://localhost:* http://127.0.0.1:*;"
    Access-Control-Allow-Origin = "*"

