name = "yohelab-demo"
type = "javascript"
main = "src/index.js"
compatibility_date = "2024-04-01"

[env.production]
routes = [
  { pattern = "yohelab-demo.pages.dev", zone_name = "pages.dev" }
]

[build]
command = ""
cwd = ""
watch_paths = []

[build.upload]
format = "service-worker"
